[auth]
username = "Kowalski"
password = "labor"

[gcp_service_account]
type = "service_account"
project_id = "pesquisa-labor"
private_key_id = "416de83105d1c71307292b2a2a5549f4369daf76"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDNOsAqEdsC3Kzo
nqEDNTq7bBeGZ6cViY6U3nzKxTJkssKa3izdWNiM2G90dC20Raie/FOlu8vJZ2QK
XSH5rFdYf7bIbS4SP9Me3tEdbQcTncG1D/U8krAEar03dbiel48rIXsZJkqqd0Ev
IEFQuYmJPaPumMP4tLgKnAIB95xDpBBZdsXAA61LaxBzE4h4C5dbdDhFoRwA+S92
EQimUe9HQKO7rPPnkCAK8nY60KHcmcUmzyRBuiVwfAh7LII/l3l7MfU4EJHCsQFi
oe3svWjUfeWaDQap3zi0ggwoWOEsNgvSnf9DvQ8Mkhz0BeNrtxaCTOEoXoZrYFdA
EU6grcMlAgMBAAECggEANgZVN73jjWlSCxpXAGUuxM+7kaIPldfUNNQsvaQTk/aK
zAHYhZwxxUHkdR9wOJhtvwxlaKd7CdWxvBiwLO11QNK95xz2l889YE7/dWOSDVPl
/ifpQrzKoR8IGGVg6D61bYEuynwOA7nI6wLurrVowzv6v4BvdjT8ja5ryODJvfQl
eQZLM4f73Ddrc+dtLPNbP9Oo+m6mdxvlOdrfvY6JNTcHEAq98okYiV7lMaOvoE/T
luUeRIkNTol3khe+IgoQ1ppGLG1AIwcQqIn8ucQZ1Mp2jdmBHxXGnUgqC48QIual
gI81HHnklkYnMG5lFcteBEixxZcZZTcRWK/2dqQuMQKBgQD0z5q2L+vvOJHRvTdO
TAu8jI2wBZaCkFA/kMlcwXwYqoCTB/zbWIG9lG9YePc/4Td4rnGp7heHqvYORLDQ
K4hmDrvHdmri1W4UvDU33Q653XCrufhsiCh7ODBuVAvpOhHY+83ZNVCVa21GakNM
sZYBBqk1U1XScTY8SyMn3eU49wKBgQDWnAadg5Sx1+tacH2KDwateQeFm4N+Oqu4
ya2e1Ez7p18TB9O9MRxYz43DHRC+GgT+UWrf+l/uzD+rVgLYN6tQ5+8iM48PfnTo
BrgiF4FIU4XnyDf+QW0OC4CTn9Bi0Nxuj/3T2o/VzlUDUClt40F+qn1qcqtK6dW5
JIOPyAbZwwKBgQDY4nfxQkFm3Roq09SElFCtiWQZdsniABJoTlBm0a+sdpmUKTZ1
6VJ/71o56mk5+cBYNUvTvXCxK9/zwh1XP8oGiLUJwDpvnaB51EfdpwVd2vXv3cFd
/b7Hc39Mrz8iL+UR8/tpnJc42USlZo0bDBWV8R3FdYAKAWyIPBT4Q9jI/wKBgCRo
R78FCX66MJUhLEr1jZ50P9Bst3v8nBE3NZsSTRUMKdbipwsbf8GZRGVrUuHNLDew
vD7PDONIBy0b5FOl7gxFrI3SzVxFibOrICW4cxhAAyF1F/qsQsH1NZTVsdZxtFOV
XexI0cnlvQpY2Q5pVT0V0zzxwxlsXfOQvDjyKCddAoGBAJdJ2s1NdQCow2Xi/DaN
Wrn208PyGqyE5NbcgG5/Q0cpEhMcgqbojKxfVOC1NRybp7L7y/CmCanRA/Cz1b/a
ESHSa3GCoYOA0n0+H3Jd0PRRNEG7uQk1QgxrmMO7ZRQUTuVIFH5absTT2q4sGRd4
zWaxzc1p8KKDDryqMu+G3H2A
-----END PRIVATE KEY-----"""
client_email = "streamlit-labor@pesquisa-labor.iam.gserviceaccount.com"
client_id = "116065743735628478795"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-labor%40pesquisa-labor.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
