[auth]
username = "Kowalski"
password = "labor"

[gcp_service_account]
type = "service_account"
project_id = "pesquisa-labor"
private_key_id = "COLE_AQUI_O_PRIVATE_KEY_ID_NOVO"
private_key = """-----BEGIN PRIVATE KEY-----
COLE_AQUI_A_NOVA_PRIVATE_KEY_COMPLETA
-----END PRIVATE KEY-----
"""
client_email = "streamlit-labor@pesquisa-labor.iam.gserviceaccount.com"
client_id = "116065743735628478795"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-labor%40pesquisa-labor.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
